# Generated by Django 4.0.6 on 2022-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='timeToCook',
            field=models.CharField(max_length=20),
        ),
    ]
