# Generated by Django 4.0.6 on 2022-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_meal_course_alter_meal_mealname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='steps',
            field=models.TextField(),
        ),
    ]
